import sqlite3
from datetime import datetime
DB_NAME = 'diacare_demo.db'
def create_database():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute()
    cursor.execute()
    cursor.execute()
    cursor.execute()
    conn.commit()
    conn.close()
    print("✅ Database created successfully!")
def insert_sample_data():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute(, ('P001', 'John Doe', '+91-9876543210', 'john@example.com'))
    cursor.execute(, ('P001', 45, 75.5, 1.75, 24.7, 95, 5.5, 'moderate', 25, 'Low'))
    cursor.execute(, ('P001', 25, 'Low', 85, 75))
    cursor.execute(, ('P001', 'glucose', 'Glucose within optimal range', 'low'))
    conn.commit()
    conn.close()
    print("✅ Sample data inserted!")
def query_patient_data():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    print("\n📊 PATIENT RECORDS:")
    cursor.execute('SELECT * FROM patients')
    for row in cursor.fetchall():
        print(f"ID: {row[0]}, Name: {row[2]}, Phone: {row[3]}")
    print("\n📊 HEALTH RECORDS:")
    cursor.execute('SELECT * FROM health_records')
    for row in cursor.fetchall():
        print(f"Patient: {row[1]}, Sugar: {row[6]}, HbA1c: {row[7]}, Risk: {row[10]}")
    print("\n📊 PREDICTIONS:")
    cursor.execute('SELECT * FROM predictions')
    for row in cursor.fetchall():
        print(f"Patient: {row[1]}, Risk Score: {row[2]}, Health Score: {row[4]}")
    print("\n📊 ALERTS:")
    cursor.execute('SELECT * FROM alerts')
    for row in cursor.fetchall():
        print(f"Patient: {row[1]}, Alert: {row[3]}, Severity: {row[4]}")
    conn.close()
def advanced_queries():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    print("\n🔍 ADVANCED QUERY 1: Patients with High Risk")
    cursor.execute()
    print(cursor.fetchall())
    print("\n🔍 ADVANCED QUERY 2: Average Health Metrics")
    cursor.execute()
    print(cursor.fetchall())
    print("\n🔍 ADVANCED QUERY 3: Patient History with Trends")
    cursor.execute()
    print(cursor.fetchall())
    print("\n🔍 ADVANCED QUERY 4: Alert Summary by Severity")
    cursor.execute()
    print(cursor.fetchall())
    conn.close()
def update_and_delete_demo():
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    print("\n✏️ UPDATE DEMO: Updating patient phone number")
    cursor.execute()
    print("\n🗑️ DELETE DEMO: Deleting old alerts")
    cursor.execute()
    conn.commit()
    conn.close()
    print("✅ Update and Delete operations completed!")
if __name__ == '__main__':
    print("=" * 60)
    print("SQLite DATABASE DEMONSTRATION FOR DIACARE AI")
    print("=" * 60)
    create_database()
    insert_sample_data()
    query_patient_data()
    advanced_queries()
    update_and_delete_demo()
    print("\n" + "=" * 60)
    print("✅ DATABASE DEMONSTRATION COMPLETE!")
    print("=" * 60)
    print("\nNote: This is a DEMO file for educational purposes.")
    print("The actual application uses browser localStorage for data storage.")
